# -*- coding: utf-8 -*-
"""NLP speech tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IibpwBUWO8ANBkk6PIcoHXJMIBWV5rR4
"""

import re
import nltk.util

s=" hallo people of good kenya"

from nltk.util import ngrams

s = s.lower()

tokens = [token for token in s.split(" ") if token != ""]

output = list(ngrams(tokens, 3))

print(output)

