# -*- coding: utf-8 -*-
"""POS tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqGmRBL9d9KGr-_aSnLEqadZetWtyzjH
"""

import nltk

nltk.download('punkt')

nltk.download('averaged_perceptron_tagger')

text = " They refuse to permit us to obtain the refuse permit "

lower_case = text.lower()

tokens = nltk.word_tokenize(lower_case)

tags = nltk.pos_tag(tokens)

print(tags)

